# Generated by Django 3.2.16 on 2022-12-13 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cart',
        ),
    ]
