# Generated by Django 3.2.16 on 2022-12-15 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0006_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='billing_details',
            fields=[
                ('billing_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('shipping_initiated', models.BooleanField(default=False)),
                ('shipped', models.BooleanField(default=False)),
                ('billing_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.billing_details')),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopping.cart')),
            ],
        ),
    ]
