# Generated by Django 4.2.5 on 2023-10-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_remove_cart_razor_pay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
